/**
 * UF (user-flavored) Ollama variant.
 *
 * `npm install` / `npm run setup` writes agent/UF/Modelfile and builds a
 * custom Ollama model from it — the automated equivalent of:
 *
 *     ollama create qwen-yoru -f agent/UF/Modelfile
 *
 * The variant is used ONLY for chat when OLLAMA_UF_ENABLED=true; reasoning
 * and code models are untouched, and setting the flag back to false returns
 * the agent to the plain base model.
 */
import path from "node:path";
import { promises as fs } from "node:fs";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));

export const UF = {
  baseModel: "qwen2.5:1.5b",
  model: "qwen-yoru",
  dir: path.resolve(HERE, "..", "UF"),
};
UF.modelfile = path.join(UF.dir, "Modelfile");

// Rude/witty persona baked into the variant. Plain personality only —
// no jailbreak-style instructions. Brevity is enforced here too: short
// answers are the single biggest lever on local reply latency.
const UF_SYSTEM = [
  "You are YORU — a rude, sarcastic, witty smartass of an AI assistant, but genuinely intelligent and useful.",
  "Default to VERY SHORT, punchy replies (1-3 sentences) for casual chat. Go longer only when the topic truly needs it (code, explanations).",
  "No corporate tone, no 'as an AI' disclaimers, no filler, no restating the question. If someone is rude, roast them back and still answer the substance.",
  "Be direct and honest. Never fabricate facts or tool results.",
].join("\n");

export function ufModelfileContents() {
  return [
    "# YORU UF variant — generated by npm install / npm run setup.",
    "# Rebuilt automatically from this file; edit and re-run `npm run setup` to change it.",
    "",
    `FROM ${UF.baseModel}`,
    "",
    "# Tuned for lightning-fast replies (1-10s wall clock on modest GPUs)",
    "PARAMETER temperature 0.7",
    "PARAMETER top_p 0.9",
    "PARAMETER num_ctx 1536",
    "PARAMETER num_predict 140",
    "PARAMETER repeat_penalty 1.2",
    "",
    // Keep the triple quotes INLINE with the text — `SYSTEM """` on its own
    // line breaks the Modelfile parser on some Ollama builds ("neither
    // 'from' or 'files' was specified" from /api/create).
    `SYSTEM """${UF_SYSTEM}"""`,
    "",
  ].join("\n");
}

/** Write agent/UF/Modelfile (idempotent). Returns the path. */
export async function writeUfModelfile() {
  await fs.mkdir(UF.dir, { recursive: true });
  await fs.writeFile(UF.modelfile, ufModelfileContents(), "utf8");
  return UF.modelfile;
}

async function ollamaTags(url) {
  const res = await fetch(`${url}/api/tags`, { signal: AbortSignal.timeout(5000) });
  if (!res.ok) throw new Error(`tags → ${res.status}`);
  const body = await res.json();
  return (body.models || []).map((m) => m.name);
}

async function pullIfMissing(url, installed, name) {
  if (installed.includes(name) || installed.includes(`${name}:latest`)) return false;
  const res = await fetch(`${url}/api/pull`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ name, stream: false }),
    signal: AbortSignal.timeout(30 * 60 * 1000),
  });
  if (!res.ok) throw new Error(`pull ${name} → ${res.status}`);
  return true;
}

/**
 * Creates the variant from the Modelfile. Tries the HTTP API first (sending
 * both `model` and the legacy `name` field), then falls back to the
 * `ollama create` CLI with the on-disk Modelfile when the API rejects the
 * payload — older daemons are picky about inline modelfile bodies.
 */
export async function createUfVariant(url) {
  const base = String(url || "http://127.0.0.1:11434").replace(/\/$/, "");
  const modelfile = ufModelfileContents();
  try {
    const res = await fetch(`${base}/api/create`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ model: UF.model, name: UF.model, modelfile, stream: false }),
      signal: AbortSignal.timeout(10 * 60 * 1000),
    });
    if (!res.ok) throw new Error(`${res.status}: ${(await res.text()).slice(0, 200)}`);
    return;
  } catch (apiErr) {
    // CLI fallback
    const { spawnSync } = await import("node:child_process");
    const out = spawnSync("ollama", ["create", UF.model, "-f", UF.modelfile], { encoding: "utf8" });
    if (out.error || out.status !== 0) {
      throw new Error(`${apiErr.message} | cli fallback failed: ${(out.stderr || out.error?.message || "").slice(0, 200)}`);
    }
  }
}

/**
 * Build the UF variant from agent/UF/Modelfile via the Ollama API
 * (equivalent to `ollama create qwen-yoru -f agent/UF/Modelfile`).
 * Skips the build when the variant already exists — a fresh `npm run setup`
 * after editing the Modelfile forces a rebuild.
 */
export async function ensureUfModel({ url, force = false, log = console.log } = {}) {
  const base = String(url || "http://127.0.0.1:11434").replace(/\/$/, "");
  await writeUfModelfile();
  let installed;
  try {
    installed = await ollamaTags(base);
  } catch {
    log(`[uf] ollama not reachable at ${base} — Modelfile written; variant will build on next setup with ollama running`);
    return { created: false, reason: "ollama-offline" };
  }
  // Rebuild automatically when the Modelfile changed (e.g. new speed tuning),
  // so an existing qwen-yoru doesn't keep stale parameters.
  const { createHash } = await import("node:crypto");
  const hashFile = path.join(UF.dir, ".build-hash");
  const hash = createHash("sha256").update(ufModelfileContents()).digest("hex");
  const previous = await fs.readFile(hashFile, "utf8").catch(() => "");
  const exists = installed.includes(UF.model) || installed.includes(`${UF.model}:latest`);
  if (!force && exists && previous.trim() === hash) {
    return { created: false, reason: "exists" };
  }
  await pullIfMissing(base, installed, UF.baseModel);
  await createUfVariant(base);
  await fs.writeFile(hashFile, hash, "utf8").catch(() => {});
  return { created: true, model: UF.model, rebuilt: exists };
}

/** Chat model to use right now, honoring the UF toggle. */
export function resolveUfChatModel(config) {
  const o = config?.providers?.ollama;
  if (o?.uf?.enabled) return o.uf.model;
  return o?.model || UF.baseModel;
}
